name: Kelly Hungerford
favicon: null
layout_spectrum: 0.51455
typography_spectrum: 0.6154321888461709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9ee2ed'
    - '#fe698f'
    - '#aa0000'
    - '#090000'
    - '#6a413a'
  brandStrength: 0.5
  lightness: 0.14787077624350786
  saturation: 0.8901498212944716
  rhythmicContrast: 0.2057088385336101
purpose: []
