name: Kelly Hungerford
favicon: null
layout_spectrum: 0.2999178608879447
typography_spectrum: 0.6154321888461709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.059687769273296
  lightness: 0.14787077624350786
  saturation: 0.8901498212944716
  rhythmicContrast: 0.2057088385336101
purpose: []
